apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: app
      image: gcr.io/distroless/static
      command: ["sleep", "3600"]


# inject debug container
#  kubectl debug -it my-app \
#  --target=app \
#  --image=busybox \
#  --name=debugger